version: '3.8'
services:
  #db:
   # image: postgres:13
    #restart: unless-stopped
    #environment:
     # - POSTGRES_DB=labelstudio2
     # - POSTGRES_USER=postgres
     # - POSTGRES_PASSWORD=yourpassword
    #ports:
     # - "5432:5432"
  app:
    image: your-repo/label-studio:latest
    restart: unless-stopped
    ports:
      - "8300:8000"
    environment:
      - DJANGO_DB=default
      - POSTGRE_NAME=labelstudio2
      - POSTGRE_USER=postgres
      - POSTGRE_PASSWORD=yourpassword
      - POSTGRE_PORT=5432
      - POSTGRE_HOST=labelstudio2.cd4g2mag86z9.ap-southeast-1.rds.amazonaws.com
      - LABEL_STUDIO_HOST=localhost
      - JSON_LOG=1
    command: label-studio-uwsgi
    # Add any required volumes for persistent data or configs
    # volumes:
    #   - ./mydata:/label-studio/data:rw
