services:
  app:
    stdin_open: true
    tty: true
    build: .
    image: heartexlabs/label-studio:latest
    restart: unless-stopped
    ports:
      - "8080:8000" # Maps host port 8080 to container port 8000
    environment:
      - DJANGO_DB=default
      - POSTGRE_NAME=labelstudio2
      - POSTGRE_USER=postgres
      - POSTGRE_PASSWORD=postgres1
      - POSTGRE_PORT=5432
      - POSTGRE_HOST=database-1.cpugm02gy8x7.ap-southeast-1.rds.amazonaws.com
      - LABEL_STUDIO_HOST=${LABEL_STUDIO_HOST:-}
      - JSON_LOG=1
    volumes:
      - ./mydata:/label-studio/data:rw
    entrypoint: /bin/sh
    command: -c "chmod +x ./deploy/docker-entrypoint.sh && ./deploy/docker-entrypoint.sh label-studio --port 8000"
