title: HTML NER Tagging
type: community
group: Community Contributions
image: /static/templates/community-contributions/html-ner-tagging-person-and-organization.jpg
details: <h1>HTML NER Tagging</h1>
source_repo: https://github.com/humanSignal/awesome-label-studio-config/tree/main/label-configs/html-ner-tagging-person-and-organization
config: |
  <View>
  <!-- Template sourced from awesome-label-studio-config repository: https://github.com/humanSignal/awesome-label-studio-config/tree/main/label-configs/html-ner-tagging-person-and-organization -->
  
    <HyperTextLabels name="ner" toName="text">
      <Label value="Person" background="green"/>
      <Label value="Organization" background="blue"/>
    </HyperTextLabels>
  
    <View style="border: 1px solid #CCC;
                 border-radius: 10px;
                 padding: 5px">
      <HyperText name="text" value="$text"/> 
                </View>
  </View>
  
  
  <!-- [
    {
      "text": "<h1>John works at Acme Inc.</h1><p>He lives in New York.</p>"
    },
    {
      "text": "<div>Mary Smith is employed at BetaCorp.</div><p>They are located in San Francisco.</p>"
    }
  ]
  -->
