# Generated by Django 5.1.12 on 2025-11-04 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0008_workspace_workspacemember_and_more"),
        ("projects", "0030_project_search_vector_index"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="workspace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="projects",
                to="organizations.workspace",
            ),
        ),
        migrations.AddField(
            model_name="projectmember",
            name="workspace_member",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="created_project_members",
                to="organizations.workspacemember",
            ),
        ),
    ]
