# Generated by Django 5.1.12 on 2025-09-17 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0006_alter_organizationmember_deleted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationmember",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("admin", "Admin"),
                    ("reviewer", "Reviewer"),
                    ("annotator", "Annotator"),
                    ("inactive", "Inactive"),
                ],
                default="inactive",
                help_text="Role of the user in the organization",
                max_length=20,
                verbose_name="role",
            ),
        ),
    ]
