# Generated by Django 5.1.12 on 2025-11-04 10:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0007_add_role_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="organizationmember",
            index=models.Index(
                fields=["user", "organization", "deleted_at"],
                name="org_member_lookup_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="organizationmember",
            index=models.Index(
                fields=["organization", "role"], name="org_member_role_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationmember",
            index=models.Index(fields=["role"], name="org_member_global_role_idx"),
        ),
    ]
