# Generated by Django 5.1.12 on 2025-11-04 04:06

import core.utils.common
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0007_add_role_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Workspace",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=1000, verbose_name="workspace title"),
                ),
                (
                    "token",
                    models.CharField(
                        blank=True,
                        default=core.utils.common.create_hash,
                        max_length=256,
                        null=True,
                        unique=True,
                        verbose_name="token",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "contact_info",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="contact info",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkspaceMember",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        db_index=True,
                        default=None,
                        help_text="Timestamp indicating when the workspace member was marked as deleted. If NULL, the member is not considered deleted.",
                        null=True,
                        verbose_name="deleted at",
                    ),
                ),
            ],
            options={
                "ordering": ["pk"],
            },
        ),
        migrations.AddIndex(
            model_name="organizationmember",
            index=models.Index(
                fields=["user", "organization", "deleted_at"],
                name="org_member_lookup_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="organizationmember",
            index=models.Index(
                fields=["organization", "role"], name="org_member_role_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationmember",
            index=models.Index(fields=["role"], name="org_member_global_role_idx"),
        ),
        migrations.AddField(
            model_name="workspace",
            name="created_by",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workspace",
                to=settings.AUTH_USER_MODEL,
                verbose_name="created_by",
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workspaces",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="workspacemember",
            name="user",
            field=models.ForeignKey(
                help_text="User ID",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wm_through",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="workspacemember",
            name="workspace",
            field=models.ForeignKey(
                help_text="Workspace ID",
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.workspace",
            ),
        ),
        migrations.AddField(
            model_name="workspace",
            name="users",
            field=models.ManyToManyField(
                related_name="workspaces",
                through="organizations.WorkspaceMember",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
