title: NER Tagging for Invoices (BIO Format)
type: community
group: Community Contributions
image: /static/templates/community-contributions/ner-tagging-invoices-bio-format.jpg
details: <h1>NER Tagging for Invoices (BIO Format)</h1>
source_repo: https://github.com/humanSignal/awesome-label-studio-config/tree/main/label-configs/ner-tagging-invoices-bio-format
config: |
  <View style="display: flex; align-items: flex-start; gap: 1em;">
  <!-- Template sourced from awesome-label-studio-config repository: https://github.com/humanSignal/awesome-label-studio-config/tree/main/label-configs/ner-tagging-invoices-bio-format -->
  
    <!-- Left panel: labels + filter -->
    <View style="min-width: 250px; padding: 0.5em; background: #f7f7f7; border-radius: 4px;">
      <Header value="NER Tags" />
      <Labels name="ner" toName="text" showInline="false">
        <Label value="B-NIF"    background="#FF5733" />
        <Label value="B-FORN"   background="#33FF57" />
        <Label value="B-DATA"   background="#3375FF" />
        <Label value="B-VALOR"  background="#FF33A1" />
        <Label value="B-NUMFAT" background="#F3FF33" />
        <Label value="I-NIF"    background="#FF5733" />
        <Label value="I-FORN"   background="#33FF57" />
        <Label value="I-DATA"   background="#3375FF" />
        <Label value="I-VALOR"  background="#FF33A1" />
        <Label value="I-NUMFAT" background="#F3FF33" />
        <Label value="O"        background="#aaa"    />
      </Labels>
    </View>
  
    <!-- Right panel: text to annotate -->
    <View style="flex: 1; max-height: 80vh; overflow-y: auto;">
      <Text
        name="text"
        value="$ocr"
        granularity="word"
      />
    </View>
  </View>
  
  <!-- [
      {
        "text": "INVOICE\n\nInvoice # 12345       Date 04/24/2024\n\nVendor\nItalian Restaurant\n123 Main Street\n123-455-7980\n\nDESCRIPTION   QTY   UNT   AMOUNT\nSpaghetti alia Carbonara     1     15.00   $15.00\nSpaghetti alla Matriciana    1     15.00   $15.00\nSaltimbocca alla Romana      1     20.00   $20.00\nSalad                        1      4.00   $4.00\n\n                          $66.54\n\nTax (22%)                            $6.54\n\nTotal"
      }
    ]
  -->
