# Generated by Django 5.1.12 on 2025-11-04 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workplace_RBAC_extension", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="workspace",
            new_name="workspace_organiz_c01df0_idx",
            old_name="workspace_organiz_3c4d2e_idx",
        ),
        migrations.RenameIndex(
            model_name="workspace",
            new_name="workspace_title_28d41f_idx",
            old_name="workspace_title_1a2b3c_idx",
        ),
        migrations.RenameIndex(
            model_name="workspacemember",
            new_name="workspace_m_workspa_22cd36_idx",
            old_name="workspace_me_workspa_5e8f3c_idx",
        ),
        migrations.RenameIndex(
            model_name="workspacemember",
            new_name="workspace_m_user_id_a1ab8a_idx",
            old_name="workspace_me_user_id_4a2b1d_idx",
        ),
        migrations.RenameIndex(
            model_name="workspaceproject",
            new_name="workspace_p_workspa_841c52_idx",
            old_name="workspace_pr_workspa_7c9c5e_idx",
        ),
        migrations.RenameIndex(
            model_name="workspaceproject",
            new_name="workspace_p_project_219597_idx",
            old_name="workspace_pr_project_2a3e8b_idx",
        ),
        migrations.AlterField(
            model_name="workspacemember",
            name="workspace",
            field=models.ForeignKey(
                help_text="Workspace the user belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="members",
                to="workplace_RBAC_extension.workspace",
            ),
        ),
        migrations.AlterField(
            model_name="workspaceproject",
            name="workspace",
            field=models.ForeignKey(
                help_text="Workspace containing this project",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workspace_projects",
                to="workplace_RBAC_extension.workspace",
            ),
        ),
    ]
